import { useEffect, useMemo, useState } from 'react';
import { Activity, BriefcaseBusiness, BrainCircuit, CheckCircle2, ChevronRight, CircleUserRound, FileText, Home, Menu, Network, Search, Settings, Sparkles, Target, X } from 'lucide-react';
import { careers, employers, jobSources, skills } from './data/catalog';
import { isSupabaseConfigured } from './lib/supabase';
import './styles.css';

type Tab = 'home'|'skills'|'careers'|'roadmap'|'resume'|'jobs'|'tracker'|'ai'|'profile';
const nav: {id:Tab; label:string; icon:any}[] = [{id:'home',label:'Home',icon:Home},{id:'skills',label:'Skills',icon:Target},{id:'careers',label:'Careers',icon:BriefcaseBusiness},{id:'roadmap',label:'AI Roadmap',icon:BrainCircuit},{id:'resume',label:'AI & ATS Resume',icon:FileText},{id:'jobs',label:'Live Jobs',icon:Search},{id:'tracker',label:'Application Tracker',icon:Activity},{id:'ai',label:'AI Hub',icon:Sparkles},{id:'profile',label:'Profile & Settings',icon:Settings}];
function App(){
 const [tab,setTab]=useState<Tab>('home'); const [menu,setMenu]=useState(false); const [query,setQuery]=useState('');
 const [selected,setSelected]=useState<string[]>(()=>JSON.parse(localStorage.getItem('careeros-skills')||'[]'));
 useEffect(()=>localStorage.setItem('careeros-skills',JSON.stringify(selected)),[selected]);
 const progress=Math.round(selected.length/skills.length*100); const filtered=useMemo(()=>skills.filter(x=>x.toLowerCase().includes(query.toLowerCase())),[query]);
 const choose=(id:Tab)=>{setTab(id);setMenu(false)};
 return <div className="app"><aside className={menu?'open':''}><div className="brand"><div className="logo">C</div><div><b>CareerOS</b><small>ULTIMATE</small></div><button className="close" onClick={()=>setMenu(false)}><X size={18}/></button></div><nav>{nav.map(n=><button className={tab===n.id?'active':''} onClick={()=>choose(n.id)} key={n.id}><n.icon size={18}/><span>{n.label}</span></button>)}</nav><div className="side-foot">Built by <b>Saket Yadav</b><br/>Maccy Creations</div></aside><main><header><button className="menu" onClick={()=>setMenu(true)}><Menu/></button><div><span className="eyebrow">YOUR CAREER OPERATING SYSTEM</span><h1>{nav.find(n=>n.id===tab)?.label}</h1></div><div className="status"><span className="dot"/> Offline-ready</div></header><section className="content">{tab==='home'&&<HomeView progress={progress} selected={selected} go={choose}/>} {tab==='skills'&&<Skills query={query} setQuery={setQuery} filtered={filtered} selected={selected} setSelected={setSelected}/>} {tab==='careers'&&<Careers selected={selected}/>} {tab==='roadmap'&&<AI title="AI Roadmap" text="Generate a grounded learning plan from your selected skills. Connect a server-side AI provider in Settings to enable generation."/>} {tab==='resume'&&<AI title="AI & ATS Resume" text="Paste your experience to receive evidence-based ATS feedback. Your data stays local until you connect Supabase."/>} {tab==='jobs'&&<Jobs/>} {tab==='tracker'&&<Tracker/>} {tab==='ai'&&<AIHub/>} {tab==='profile'&&<Profile/>}</section></main></div>
}
function HomeView({progress,selected,go}:{progress:number;selected:string[];go:(x:Tab)=>void}){return <><div className="hero"><div><span className="pill">✦ PRIVATE • EVIDENCE-BASED</span><h2>Build a career<br/><em>that moves.</em></h2><p>A focused workspace for skills, applications and responsible AI guidance.</p><button className="primary" onClick={()=>go('skills')}>Plan my next step <ChevronRight size={17}/></button></div><div className="ring"><strong>{progress}%</strong><span>skill progress</span></div></div><div className="grid"><Card title="Your momentum" value={`${selected.length} skills`} note="tracked locally" icon={<Activity/>}/><Card title="Applications" value="0 active" note="Add your first application" icon={<BriefcaseBusiness/>}/><Card title="Next best action" value="Choose a skill" note="Start with your goals" icon={<Sparkles/>}/></div><div className="section-head"><div><span className="eyebrow">DESIGNED FOR TRUST</span><h3>No fabricated job data</h3></div></div><div className="notice"><CheckCircle2/><div><b>Live jobs only arrive from configured providers.</b><p>CareerOS never invents listings, salary data or company claims. Connect approved APIs through a secure backend to activate Live Jobs.</p></div></div></>}
function Card({title,value,note,icon}:{title:string;value:string;note:string;icon:any}){return <div className="card"><div className="icon">{icon}</div><span>{title}</span><strong>{value}</strong><small>{note}</small></div>}
function Skills({query,setQuery,filtered,selected,setSelected}:{query:string;setQuery:(x:string)=>void;filtered:readonly string[];selected:string[];setSelected:(x:string[])=>void}){return <><div className="toolbar"><p>Track the capabilities you want to build. Your selections are stored offline on this device.</p><div className="search"><Search size={17}/><input placeholder="Search skills" value={query} onChange={e=>setQuery(e.target.value)}/></div></div><div className="skill-grid">{filtered.map(s=><button className={'skill '+(selected.includes(s)?'chosen':'')} onClick={()=>setSelected(selected.includes(s)?selected.filter(x=>x!==s):[...selected,s])} key={s}>{selected.includes(s)?<CheckCircle2 size={17}/>:<span className="empty"/>}{s}</button>)}</div></>}
function Careers({selected}:{selected:string[]}){return <><p className="lead">Career directions aligned to your selected skills. Recommendations are rule-based and transparent.</p><div className="career-grid">{careers.map(c=>{const matches=c.skills.filter(s=>selected.includes(s));return <article className="career"><div className="career-top"><Network/><span>{matches.length} matching</span></div><h3>{c.title}</h3><div>{c.skills.map(s=><span className={matches.includes(s)?'tag match':'tag'}>{s}</span>)}</div></article>})}</div></>}
function AI({title,text}:{title:string;text:string}){return <div className="empty-state"><div className="big-icon"><BrainCircuit size={34}/></div><h2>{title}</h2><p>{text}</p><button className="primary">Configure secure AI connection <ChevronRight size={17}/></button></div>}
function Jobs(){return <><div className="jobs-head"><div><span className="eyebrow">VERIFIED SOURCES ONLY</span><h2>Live job search</h2><p>Connect provider credentials on the server to fetch current results. No demo listings are shown.</p></div><button className="primary"><Search size={17}/> Configure sources</button></div><div className="source-list">{jobSources.map(s=><div><span className="source-dot"/>{s}<small>not connected</small></div>)}</div></>}
function Tracker(){return <div className="empty-state"><div className="big-icon"><Activity size={34}/></div><h2>Your application pipeline</h2><p>Track roles from discovery to offer. Add an application to begin; records are safe offline and can sync to Supabase.</p><button className="primary">Add application <ChevronRight size={17}/></button></div>}
function AIHub(){return <><div className="hero compact"><div><span className="pill">RESPONSIBLE AI</span><h2>Use AI as a <em>copilot.</em></h2><p>Provider-neutral tools with citations, source links and clear uncertainty states.</p></div></div><div className="provider-grid">{['OpenAI / ChatGPT','Google Gemini','Superhuman AI','Custom provider'].map(x=><div className="provider"><Sparkles size={19}/><b>{x}</b><span>Connect via secure Edge Function</span></div>)}</div></>}
function Profile(){return <><div className="profile-card"><div className="avatar">SY</div><div><h2>Saket Yadav</h2><p>CareerOS Ultimate · Maccy Creations</p></div></div><div className="settings"><div><b>Cloud sync</b><span>Supabase {isSupabaseConfigured?'configured':'not configured'} · offline mode remains available</span></div><div><b>Account</b><span>Email/password login and logout via Supabase Auth</span></div><div><b>About & contact</b><span>CAREEROSULTIMATE@gmail.com</span></div><div><b>Privacy</b><span>Your local data is stored on this device. Review your privacy policy before launch.</span></div></div></>}
export default App;
