import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react';
import { Activity, ArrowRight, BrainCircuit, BriefcaseBusiness, Check, FileText, Home, LogIn, LogOut, Menu, Search, Settings, ShieldCheck, Sparkles, Target, X } from 'lucide-react';
import { careers, employers, jobSources, skills } from './data/catalog';
import { signInWithPassword, signOut, signUpWithPassword, supabase } from './lib/supabase';
import './styles.css';

type Tab = 'home'|'skills'|'careers'|'roadmap'|'resume'|'jobs'|'tracker'|'ai'|'profile';
type Status = 'Saved'|'Applied'|'Interview'|'Offer'|'Rejected'|'Withdrawn';
type Application = { id:string; company:string; role:string; status:Status; source:string; date:string; url?:string };
type Job = { title:string; company:string; location:string; url:string; source:string; description?:string; postedAt?:string };
const nav = [{id:'home',label:'Home',icon:Home},{id:'skills',label:'Skills',icon:Target},{id:'careers',label:'Career paths',icon:BriefcaseBusiness},{id:'roadmap',label:'AI roadmap',icon:BrainCircuit},{id:'resume',label:'AI & ATS resume',icon:FileText},{id:'jobs',label:'Live jobs',icon:Search},{id:'tracker',label:'Application tracker',icon:Activity},{id:'ai',label:'AI hub',icon:Sparkles},{id:'profile',label:'Profile & settings',icon:Settings}] as const;
const read = <T,>(key:string, fallback:T):T => { try { return JSON.parse(localStorage.getItem(key) || '') as T; } catch { return fallback; } };

export default function App() {
  const [tab,setTab]=useState<Tab>('home'),[menu,setMenu]=useState(false),[query,setQuery]=useState('');
  const [selected,setSelected]=useState<string[]>(()=>read('careeros-skills',[]));
  const [applications,setApplications]=useState<Application[]>(()=>read('careeros-applications',[]));
  const [session,setSession]=useState<any>(null),[authLoading,setAuthLoading]=useState(true);
  useEffect(()=>localStorage.setItem('careeros-skills',JSON.stringify(selected)),[selected]);
  useEffect(()=>localStorage.setItem('careeros-applications',JSON.stringify(applications)),[applications]);
  useEffect(()=>{ if(!supabase){setAuthLoading(false);return;} supabase.auth.getSession().then(({data})=>{setSession(data.session);setAuthLoading(false)}); const {data}=supabase.auth.onAuthStateChange((_,s)=>setSession(s)); return ()=>data.subscription.unsubscribe(); },[]);
  const filtered=useMemo(()=>skills.filter(s=>s.toLowerCase().includes(query.toLowerCase())),[query]);
  const go=(next:Tab)=>{setTab(next);setMenu(false)}; const progress=Math.round(selected.length/skills.length*100);
  return <div className="app-shell"><aside className={menu?'sidebar open':'sidebar'}><div className="brand"><div className="brand-mark">C</div><div><b>CareerOS</b><small>ULTIMATE</small></div><button className="icon-btn close" onClick={()=>setMenu(false)}><X size={18}/></button></div><nav>{nav.map(({id,label,icon:Icon})=><button className={tab===id?'nav-link active':'nav-link'} onClick={()=>go(id)} key={id}><Icon size={18}/>{label}</button>)}</nav><div className="sidebar-foot">Built for <strong>Saket Yadav</strong><span>Maccy Creations</span></div></aside><main><header><button className="icon-btn menu" onClick={()=>setMenu(true)}><Menu/></button><div><span className="eyebrow">CAREEROS ULTIMATE</span><h1>{nav.find(n=>n.id===tab)?.label}</h1></div><div className="online"><i/> {navigator.onLine?'Online':'Offline mode'}</div></header><div className="content">{tab==='home'&&<Home progress={progress} selected={selected.length} apps={applications.length} go={go}/>} {tab==='skills'&&<Skills query={query} setQuery={setQuery} filtered={filtered} selected={selected} toggle={s=>setSelected(p=>p.includes(s)?p.filter(x=>x!==s):[...p,s])}/>} {tab==='careers'&&<Careers selected={selected}/>} {tab==='roadmap'&&<Roadmap selected={selected}/>} {tab==='resume'&&<Resume selected={selected}/>} {tab==='jobs'&&<Jobs add={a=>setApplications(p=>[a,...p])}/>} {tab==='tracker'&&<Tracker items={applications} update={setApplications}/>} {tab==='ai'&&<AIHub/>} {tab==='profile'&&<Profile session={session} loading={authLoading}/>}</div></main></div>;
}
function Home({progress,selected,apps,go}:{progress:number;selected:number;apps:number;go:(t:Tab)=>void}){return <><section className="hero"><div><span className="badge"><ShieldCheck size={14}/> Evidence-first career planning</span><h2>Build a career<br/>that <em>moves.</em></h2><p>Plan skills, discover realistic career paths and track applications. CareerOS never invents job or AI data.</p><button className="primary" onClick={()=>go('skills')}>Plan my next step <ArrowRight size={17}/></button></div><div className="ring"><strong>{progress}%</strong><span>skill progress</span></div></section><div className="stats"><Stat icon={<Target/>} title="Skills selected" value={String(selected)} note="saved offline"/><Stat icon={<Activity/>} title="Applications" value={String(apps)} note="in your tracker"/><Stat icon={<ShieldCheck/>} title="Data standard" value="Verified" note="no fabricated data"/></div><section className="notice"><Check size={20}/><div><b>Private by design</b><p>Your local plan works offline. Supabase sync, verified job APIs and server-side AI are enabled only after you configure them.</p></div></section></>}
function Stat({icon,title,value,note}:{icon:ReactNode;title:string;value:string;note:string}){return <div className="stat"><div className="stat-icon">{icon}</div><small>{title}</small><strong>{value}</strong><span>{note}</span></div>}
function Skills({query,setQuery,filtered,selected,toggle}:{query:string;setQuery:(s:string)=>void;filtered:readonly string[];selected:string[];toggle:(s:string)=>void}){return <><section className="section-head"><div><span className="eyebrow">YOUR SKILL INVENTORY</span><h2>Choose what to develop</h2><p>Select skills to personalize career matches and your roadmap.</p></div><div className="count">{selected.length}<small> selected</small></div></section><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search skills..."/></div><div className="skill-grid">{filtered.map(s=><button className={selected.includes(s)?'skill selected':'skill'} onClick={()=>toggle(s)} key={s}>{selected.includes(s)?<Check size={15}/>:<span/>}{s}</button>)}</div></>}
function Careers({selected}:{selected:string[]}){const ranked=careers.map(c=>({...c,matches:c.skills.filter(s=>selected.includes(s))})).sort((a,b)=>b.matches.length-a.matches.length);return <><section className="section-head"><div><span className="eyebrow">SKILL-ALIGNED OPTIONS</span><h2>Career paths</h2><p>Matches are based only on the skills you selected.</p></div></section><div className="career-grid">{ranked.map(c=><article className="card career" key={c.title}><div className="card-top"><BriefcaseBusiness/><span>{c.matches.length}/{c.skills.length} match</span></div><h3>{c.title}</h3><p>{c.description}</p><div className="chips">{c.skills.map(s=><span className={selected.includes(s)?'chip on':'chip'} key={s}>{s}</span>)}</div></article>)}</div></>}
function Roadmap({selected}:{selected:string[]}){const focus=selected.length?selected.slice(0,6):['English communication','JavaScript/TypeScript','SQL'];return <><section className="section-head"><div><span className="eyebrow">TRANSPARENT GUIDANCE</span><h2>Your learning roadmap</h2><p>These actions are planning prompts—not fabricated claims or guaranteed outcomes.</p></div></section><div className="roadmap">{['Baseline and goal','Practice with evidence','Build a portfolio proof','Review and iterate'].map((title,i)=><article className="card step" key={title}><b>0{i+1}</b><div><h3>{title}</h3><p>{i===0?`Define your target role and current level for: ${focus.join(', ')}.`:i===1?'Schedule small weekly practice sessions and record what you learned.':i===2?'Create a real project, document decisions and publish only work you can verify.':'Review progress monthly with a mentor, trusted source or hiring professional.'}</p></div></article>)}</div></>}
function Resume({selected}:{selected:string[]}){const [text,setText]=useState(()=>read('careeros-resume',''));useEffect(()=>localStorage.setItem('careeros-resume',JSON.stringify(text)),[text]);return <><section className="section-head"><div><span className="eyebrow">AI & ATS RESUME</span><h2>Write from your evidence</h2><p>Paste your real experience. AI providers must be configured server-side before analysis.</p></div></section><div className="resume-layout"><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Paste or write your resume here..."/><aside className="card checklist"><h3>ATS checklist</h3>{['Use a clear role title','Add measurable, truthful outcomes','Match relevant skills: '+(selected.slice(0,3).join(', ')||'select skills first'),'Keep contact information current'].map(x=><p key={x}><Check size={15}/>{x}</p>)}</aside></div></>}
function Jobs({add}:{add:(a:Application)=>void}){const [q,setQ]=useState(''),[loc,setLoc]=useState('India'),[jobs,setJobs]=useState<Job[]>([]),[message,setMessage]=useState(''),[loading,setLoading]=useState(false);const search=async(e:FormEvent)=>{e.preventDefault();if(!q.trim())return;setLoading(true);setMessage('');setJobs([]);if(!supabase){setMessage('Configure Supabase and sign in to search verified provider APIs.');setLoading(false);return;}const {data,error}=await supabase.functions.invoke('jobs',{body:{query:q,location:loc}});if(error)setMessage(error.message);else{setJobs(data?.jobs||[]);setMessage(data?.message||'No verified results returned.')}setLoading(false)};return <><section className="section-head"><div><span className="eyebrow">VERIFIED PROVIDERS ONLY</span><h2>Live job search</h2><p>Results come from configured APIs; this app never creates listings.</p></div></section><form className="job-search" onSubmit={search}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Role, skill or company"/><input value={loc} onChange={e=>setLoc(e.target.value)} placeholder="Location"/><button className="primary">{loading?'Searching...':'Search jobs'}</button></form><p className="muted">{message}</p><div className="job-list">{jobs.map(j=><article className="card job" key={j.url}><div><span className="source">{j.source}</span><h3>{j.title}</h3><b>{j.company}</b><p>{j.location}</p></div><div className="job-actions"><a href={j.url} target="_blank" rel="noreferrer">Open listing</a><button onClick={()=>add({id:crypto.randomUUID(),company:j.company,role:j.title,status:'Saved',source:j.source,date:new Date().toISOString(),url:j.url})}>Track</button></div></article>)}</div><div className="provider-box"><b>Configured source families</b><p>{jobSources.join(' · ')}</p></div></>}
function Tracker({items,update}:{items:Application[];update:(x:Application[])=>void}){const [company,setCompany]=useState(''),[role,setRole]=useState('');const add=(e:FormEvent)=>{e.preventDefault();if(!company||!role)return;update([{id:crypto.randomUUID(),company,role,status:'Applied',source:'Manual',date:new Date().toISOString()},...items]);setCompany('');setRole('')};return <><section className="section-head"><div><span className="eyebrow">FOLLOW THROUGH</span><h2>Application tracker</h2><p>Saved locally first and ready to sync with Supabase.</p></div></section><form className="inline-form" onSubmit={add}><input value={company} onChange={e=>setCompany(e.target.value)} placeholder="Company"/><input value={role} onChange={e=>setRole(e.target.value)} placeholder="Role"/><button className="primary">Add application</button></form><div className="tracker">{items.length===0?<div className="empty">No applications yet. Add one manually or track a verified listing.</div>:items.map(a=><article className="card tracker-row" key={a.id}><div><b>{a.role}</b><span>{a.company} · {a.source}</span></div><select value={a.status} onChange={e=>update(items.map(x=>x.id===a.id?{...x,status:e.target.value as Status}:x))}>{['Saved','Applied','Interview','Offer','Rejected','Withdrawn'].map(s=><option key={s}>{s}</option>)}</select></article>)}</div></>}
function AIHub(){const [prompt,setPrompt]=useState(''),[answer,setAnswer]=useState(''),[loading,setLoading]=useState(false);const ask=async()=>{if(!prompt.trim()||!supabase){setAnswer('Connect Supabase and configure an approved AI provider in the Edge Function. No answer was generated.');return;}setLoading(true);const {data,error}=await supabase.functions.invoke('ai',{body:{feature:'career-assistant',prompt}});setAnswer(error?error.message:(data?.answer||'No grounded answer returned.'));setLoading(false)};return <><section className="section-head"><div><span className="eyebrow">RESPONSIBLE AI</span><h2>AI hub</h2><p>ChatGPT, Gemini and other providers belong behind the secure server gateway. Responses must expose provider and citations.</p></div></section><div className="card ai-box"><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Ask for a roadmap, interview practice or resume feedback..."/><button className="primary" onClick={ask}>{loading?'Working...':'Ask securely'} <Sparkles size={16}/></button>{answer&&<div className="answer"><b>Grounding status</b><p>{answer}</p></div>}</div></>}
function Profile({session,loading}:{session:any;loading:boolean}){const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState('');const auth=async(mode:'in'|'up')=>{try{const result=mode==='in'?await signInWithPassword(email,password):await signUpWithPassword(email,password);if(result.error)throw result.error;setMessage(mode==='in'?'Signed in. Check your inbox if confirmation is enabled.':'Account created. Check your email to confirm.')}catch(e:any){setMessage(e.message)}};return <><section className="section-head"><div><span className="eyebrow">SAKET YADAV · MACCY CREATIONS</span><h2>Profile & settings</h2><p>Contact: CAREEROSULTIMATE@gmail.com · Offline data stays on this device.</p></div></section>{loading?<p>Loading session...</p>:session?<div className="card account"><ShieldCheck/><h3>{session.user.email}</h3><p>Authenticated with Supabase. Your private records are protected by RLS.</p><button className="secondary" onClick={()=>signOut()}><LogOut size={16}/> Log out</button></div>:<div className="card auth"><LogIn/><h3>Secure account</h3><input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="Email"/><input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="Password"/><div><button className="primary" onClick={()=>auth('in')}>Log in</button><button className="secondary" onClick={()=>auth('up')}>Create account</button></div><p className="muted">{message}</p></div>}<div className="legal"><b>About · Privacy policy · Review</b><p>CareerOS Ultimate is a Maccy Creations product. Add your finalized legal policy and review workflow before public launch.</p></div></>}
