import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react';
import { Activity, BriefcaseBusiness, BrainCircuit, CheckCircle2, ChevronRight, FileText, Home, LogIn, LogOut, Menu, Network, Search, Settings, ShieldCheck, Sparkles, Target, X } from 'lucide-react';
import { careers, jobSources, skills } from './data/catalog';
import { isSupabaseConfigured, signInWithPassword, signOut, signUpWithPassword, supabase } from './lib/supabase';
import './styles.css';

type Tab = 'home'|'skills'|'careers'|'roadmap'|'resume'|'jobs'|'tracker'|'ai'|'profile';
type Status = 'Saved'|'Applied'|'Interview'|'Offer'|'Rejected'|'Withdrawn';
type Application = { id:string; company:string; role:string; status:Status; source:string; date:string; job_url?:string };
type Job = { title:string; company:string; location:string; url:string; source:string; description:string; postedAt?:string };
const nav = [{id:'home',label:'Home',icon:Home},{id:'skills',label:'Skills',icon:Target},{id:'careers',label:'Career Tab',icon:BriefcaseBusiness},{id:'roadmap',label:'AI Roadmap',icon:BrainCircuit},{id:'resume',label:'AI & ATS Resume',icon:FileText},{id:'jobs',label:'Live Job',icon:Search},{id:'tracker',label:'Application Tracker',icon:Activity},{id:'ai',label:'AI Hub',icon:Sparkles},{id:'profile',label:'Profile & Settings',icon:Settings}] as const;
const providers = ['OpenAI / ChatGPT','Google Gemini','Superhuman AI','Secure custom gateway'];

function read<T>(key:string, fallback:T):T { try { const value=localStorage.getItem(key); return value ? JSON.parse(value) as T : fallback; } catch { return fallback; } }

export default function App() {
  const [tab,setTab]=useState<Tab>('home'); const [menu,setMenu]=useState(false); const [query,setQuery]=useState('');
  const [selected,setSelected]=useState<string[]>(()=>read('careeros-selected-skills',[]));
  const [applications,setApplications]=useState<Application[]>(()=>read('careeros-applications',[]));
  const [session,setSession]=useState<any>(null); const [authLoading,setAuthLoading]=useState(true);
  useEffect(()=>{ localStorage.setItem('careeros-selected-skills',JSON.stringify(selected)); },[selected]);
  useEffect(()=>{ localStorage.setItem('careeros-applications',JSON.stringify(applications)); },[applications]);
  useEffect(()=>{ if (!supabase) { setAuthLoading(false); return; } supabase.auth.getSession().then(({data})=>{setSession(data.session);setAuthLoading(false)}); const {data}=supabase.auth.onAuthStateChange((_event,next)=>setSession(next)); return ()=>data.subscription.unsubscribe(); },[]);
  const filtered=useMemo(()=>skills.filter(s=>s.toLowerCase().includes(query.toLowerCase())),[query]);
  const progress=Math.round(selected.length/skills.length*100);
  const change=(id:Tab)=>{setTab(id);setMenu(false)};
  return <div className="app-shell"><aside className={menu?'sidebar open':'sidebar'}><div className="brand-row"><div className="brand-mark">C</div><div><div className="brand-name">CareerOS</div><div className="brand-subtitle">ULTIMATE</div></div><button className="float-icon close-btn" onClick={()=>setMenu(false)}><X size={18}/></button></div><nav className="nav-list">{nav.map(({id,label,icon:Icon})=><button key={id} className={tab===id?'nav-button active':'nav-button'} onClick={()=>change(id)}><Icon size={17}/><span>{label}</span></button>)}</nav><div className="sidebar-footer">Built for<strong>Saket Yadav</strong><span>Maccy Creations</span></div></aside><main className="main-panel"><header className="topbar"><div className="topbar-left"><button className="float-icon menu-btn" onClick={()=>setMenu(true)}><Menu size={19}/></button><div><div className="eyebrow">YOUR CAREER OPERATING SYSTEM</div><h1>{nav.find(n=>n.id===tab)?.label}</h1></div></div><div className="status-pill"><span className="pulse-dot"/>{session?'Synced account':'Offline ready'}</div></header><div className="content-wrap">
    {tab==='home'&&<Home progress={progress} selected={selected.length} applications={applications.length} go={change}/>} 
    {tab==='skills'&&<Skills query={query} setQuery={setQuery} filtered={filtered} selected={selected} toggle={s=>setSelected(p=>p.includes(s)?p.filter(x=>x!==s):[...p,s])}/>} 
    {tab==='careers'&&<Careers selected={selected}/>} {tab==='roadmap'&&<Roadmap selected={selected}/>} {tab==='resume'&&<Resume selected={selected}/>} {tab==='jobs'&&<Jobs add={a=>setApplications(p=>[a,...p])}/>} {tab==='tracker'&&<Tracker items={applications} update={setApplications}/>} {tab==='ai'&&<AIHub/>} {tab==='profile'&&<Profile session={session} loading={authLoading} />}
  </div></main></div>;
}
function Home({progress,selected,applications,go}:{progress:number;selected:number;applications:number;go:(t:Tab)=>void}) { return <><section className="hero-panel"><div><div className="pill-label">PRIVATE • EVIDENCE-BASED</div><h2>Build a career<br/>that <span>moves.</span></h2><p>CareerOS Ultimate combines skill planning, transparent career matching, verified jobs and responsible AI without inventing facts.</p><button className="primary-btn" onClick={()=>go('skills')}>Plan my next step <ChevronRight size={17}/></button></div><div className="progress-ring"><strong>{progress}%</strong><span>skill progress</span></div></section><section className="metrics-grid"><Stat title="Tracked skills" value={String(selected)} note="selected locally" icon={<Target size={18}/>}/><Stat title="Applications" value={String(applications)} note="saved locally" icon={<Activity size={18}/>}/><Stat title="Data policy" value="Verified" note="no fabricated data" icon={<ShieldCheck size={18}/>}/></section><section className="info-panel"><div className="info-icon"><CheckCircle2 size={18}/></div><div><h3>Genuine information only</h3><p>Live jobs appear only after a real approved provider returns them. Empty results are shown honestly.</p></div></section></> }
function Stat({title,value,note,icon}:{title:string;value:string;note:string;icon:ReactNode}) { return <div className="stat-card"><div className="stat-icon">{icon}</div><div className="stat-body"><span>{title}</span><strong>{value}</strong><small>{note}</small></div></div> }
function Skills({query,setQuery,filtered,selected,toggle}:{query:string;setQuery:(v:string)=>void;filtered:readonly string[];selected:string[];toggle:(s:string)=>void}) { return <><div className="toolbar-wrap"><p>Select skills to receive transparent career alignment and roadmap suggestions.</p><label className="search-box"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search skill"/></label></div><div className="skill-grid">{filtered.map(s=><button key={s} className={selected.includes(s)?'skill-chip selected':'skill-chip'} onClick={()=>toggle(s)}>{selected.includes(s)?<CheckCircle2 size={17}/>:<span className="empty-bullet"/>}<span>{s}</span></button>)}</div></> }
function Careers({selected}:{selected:string[]}) { const ranked=careers.map(c=>({...c,matches:c.skills.filter(s=>selected.includes(s))})).sort((a,b)=>b.matches.length-a.matches.length); return <><p className="section-intro">Transparent recommendations based only on your selected skills; these are guidance, not guarantees.</p><div className="career-grid">{ranked.map(c=><article className="panel-card" key={c.title}><div className="career-header"><Network size={16}/><span>{c.matches.length} matching skills</span></div><h3>{c.title}</h3><div className="tag-group">{c.skills.map(s=><span className={selected.includes(s)?'tag active':'tag'} key={s}>{s}</span>)}</div></article>)}</div></> }
function Roadmap({selected}:{selected:string[]}) { const focus=selected.length?selected:['JavaScript/TypeScript','SQL','English communication']; return <div className="roadmap-grid">{[['Foundation',['Assess current evidence',...focus.slice(0,2)]],['Execution',['Build a measurable project',...focus.slice(2,4)]],['Optimization',['Review, practice and document outcomes',...focus.slice(4,6)]]].map(([title,steps])=><div className="panel-card roadmap-card" key={title as string}><h3>{title as string}</h3><ul>{(steps as string[]).map(s=><li key={s}>{s}</li>)}</ul></div>)}</div> }
function Resume({selected}:{selected:string[]}) { const [text,setText]=useState(()=>read('careeros-resume','')); useEffect(()=>localStorage.setItem('careeros-resume',JSON.stringify(text)),[text]); const keywords=selected.filter(s=>text.toLowerCase().includes(s.toLowerCase())); return <div className="resume-layout"><div className="panel-card"><div className="resume-header"><h3>AI & ATS Resume workspace</h3><span className="score-pill">Local analysis</span></div><p className="section-intro">This local checklist is not an ATS guarantee. Connect the secure AI function for provider-backed analysis.</p><textarea value={text} onChange={e=>setText(e.target.value)} rows={14} placeholder="Paste your resume here..."/></div><div className="panel-card"><h3>Matched keywords</h3><div className="tag-group">{keywords.length?keywords.map(s=><span className="tag active" key={s}>{s}</span>):<span className="muted-text">No selected skills found in your resume yet.</span>}</div></div></div> }
function Jobs({add}:{add:(a:Application)=>void}) { const [q,setQ]=useState(''); const [loc,setLoc]=useState('India'); const [jobs,setJobs]=useState<Job[]>([]); const [loading,setLoading]=useState(false); const [message,setMessage]=useState(''); const search=async(e:FormEvent)=>{e.preventDefault();if(!q.trim())return;setLoading(true);setMessage('');setJobs([]); if(!supabase){setMessage('Connect Supabase and sign in to search verified jobs.');setLoading(false);return;} const {data,error}=await supabase.functions.invoke('jobs',{body:{query:q,location:loc}}); if(error)setMessage(error.message); else {setJobs(data?.jobs||[]);setMessage(data?.message||'No verified results returned.')} setLoading(false)}; return <><form className="jobs-header" onSubmit={search}><div><div className="eyebrow">VERIFIED SOURCES ONLY</div><h2>Live job search</h2><p>Searches configured official APIs only. No demo listings are displayed.</p></div><div className="job-form"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Role or skill"/><input value={loc} onChange={e=>setLoc(e.target.value)} placeholder="Location"/><button className="primary-btn" disabled={loading}>{loading?'Searching...':'Search jobs'}</button></div></form>{message&&<div className="info-panel"><CheckCircle2 size={18}/><p>{message}</p></div>}<div className="job-results">{jobs.map(job=><article className="panel-card" key={`${job.source}-${job.url}`}><div className="source-row"><span className="source-dot"/><strong>{job.company}</strong><small>{job.source}</small></div><h3>{job.title}</h3><p>{job.location}</p><p className="muted-text">{job.description}</p><div className="job-actions"><a className="secondary-btn" href={job.url} target="_blank" rel="noreferrer">View original</a><button className="secondary-btn" onClick={()=>add({id:crypto.randomUUID(),company:job.company,role:job.title,status:'Saved',source:job.source,date:new Date().toISOString().slice(0,10),job_url:job.url})}>Save</button></div></article>)}</div><div className="source-grid">{jobSources.map(s=><div className="panel-card source-card" key={s}><div className="source-row"><span className="source-dot"/><strong>{s}</strong></div><small>Requires approved provider access</small></div>)}</div></> }
function Tracker({items,update}:{items:Application[];update:(a:Application[])=>void}) { const [form,setForm]=useState({company:'',role:'',source:'Manual'}); const add=(e:FormEvent)=>{e.preventDefault();if(!form.company||!form.role)return;update([{id:crypto.randomUUID(),...form,status:'Applied',date:new Date().toISOString().slice(0,10)},...items]);setForm({company:'',role:'',source:'Manual'})}; return <><form className="panel-card tracker-form" onSubmit={add}><input placeholder="Company" value={form.company} onChange={e=>setForm({...form,company:e.target.value})}/><input placeholder="Role" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}/><button className="primary-btn">Add application</button></form><div className="tracker-list">{items.length?items.map(i=><div className="panel-card tracker-item" key={i.id}><div><div className="company-row"><strong>{i.company}</strong><span className={`status-badge ${i.status.toLowerCase()}`}>{i.status}</span></div><h3>{i.role}</h3><small>{i.source} • {i.date}</small></div><select value={i.status} onChange={e=>update(items.map(x=>x.id===i.id?{...x,status:e.target.value as Status}:x))}>{(['Saved','Applied','Interview','Offer','Rejected','Withdrawn'] as Status[]).map(s=><option key={s}>{s}</option>)}</select></div>):<div className="info-panel"><p>No applications saved yet. Add one manually or save a verified job.</p></div>}</div></> }
function AIHub(){ return <><section className="hero-panel compact-hero"><div><div className="pill-label">RESPONSIBLE AI</div><h2>Use AI as a <span>copilot.</span></h2><p>AI output must be clearly labelled, rate-limited, and checked against official sources before being treated as fact.</p></div></section><div className="provider-grid">{providers.map(p=><div className="panel-card provider-card" key={p}><Sparkles size={18}/><strong>{p}</strong><small>Connect through secure Supabase Edge Function</small></div>)}</div></> }
function Profile({session,loading}:{session:any;loading:boolean}) { const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [signup,setSignup]=useState(false);const submit=async(e:FormEvent)=>{e.preventDefault();setError('');try{const result=signup?await signUpWithPassword(email,password):await signInWithPassword(email,password);if(result.error)throw result.error; if(signup)setError('Account created. Check your email to confirm before signing in.');}catch(err:any){setError(err.message||'Authentication failed.')}}; return <><div className="profile-header panel-card"><div className="avatar-mark">SY</div><div><h2>Saket Yadav</h2><p>CareerOS Ultimate • Maccy Creations</p></div></div><div className="profile-grid"><div className="panel-card"><h3>Account</h3>{loading?<p>Loading account...</p>:session?<div className="auth-box"><p>Signed in as {session.user.email}</p><button className="secondary-btn" onClick={()=>signOut()}><LogOut size={16}/> Log out</button></div>:<form className="auth-form" onSubmit={submit}><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" required minLength={6} value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary-btn"><LogIn size={16}/>{signup?'Create account':'Login'}</button><button type="button" className="secondary-btn" onClick={()=>setSignup(!signup)}>{signup?'Already have an account? Login':'Create an account'}</button>{error&&<p className="error-text">{error}</p>}</form>}</div><div className="panel-card settings-panel"><h3>About & settings</h3><div className="settings-row"><span>Supabase</span><strong>{isSupabaseConfigured?'Configured':'Add .env variables'}</strong></div><div className="settings-row"><span>Contact</span><strong>CAREEROSULTIMATE@gmail.com</strong></div><div className="settings-row"><span>Privacy</span><strong>Local data stays on device until sync</strong></div></div></div></> }
